### ISSUE TITLE
[#TODO] Support more package manager

### ISSUE THREAD

**Issue by NNBnh** [NNBnh/superb-bootstrap#5]
## Current state:
https://github.com/NNBnh/superb-bootstrap/blob/fda027b3d10dca6a6337c05199d93cd05f59a561/sbb#L47-L77

## `#TODO`
- Linux:
  - [X] [Portage](https://wiki.gentoo.org/wiki/Portage#Installation) (for [Gentoo](https://www.gentoo.org))
  - [X] [Zypper](https://en.opensuse.org/Portal:Zypper) (for [OpenSUSE](https://en.opensuse.org/Main_Page))
  - [X] [Slackpkg](https://slackpkg.org) (for [Slackware](http://www.slackbook.org/html/package-management.html))
  - [X] [SBO](https://sbopkg.org) (for [Slackware](http://www.slackbook.org/html/package-management.html))
  - [x] [APK](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management) (for [Alpine](https://alpinelinux.org/about))
  - [x] [EOPKG](https://github.com/solus-project/package-management/blob/master/man/eopkg.1.md) (for [Solus](https://getsol.us/home))
  - [x] [Nix](https://nixos.org/manual/nix/stable) (for [NixOS](https://nixos.org))
  - [x] [DNF](https://rpm-software-management.github.io)
  - [x] [YUM](http://yum.baseurl.org)
  - [x] [Urpmi](https://en.wikipedia.org/wiki/Urpmi)
- BSD:
  - [X] [OpenBSD PKG](https://www.openbsd.org/faq/faq15.html) (for [OpenBSD](https://www.openbsd.org))
  - [X] [PKG NG](https://github.com/freebsd/pkg) (for [FreeBSD](https://www.freebsd.org) and [DragonFly](https://duckduckgo.com/?t=ffab&q=DragonFly&ia=web))
  - [x] [Mports](https://www.midnightbsd.org/mports) (for [MidnightBSD](http://www.midnightbsd.org))
  - [x] [PKG IN](http://www.pkgsrc.org) (for [NetBSD](https://www.netbsd.org))
- MacOS:
  - [X] [MacPorts](https://www.macports.org)
  - [X] [MAS](https://github.com/mas-cli/mas)
- Other:
  - [x] [Termux PKG](https://wiki.termux.com/wiki/Package_Management) (for [Termux](https://wiki.termux.com/wiki/Main_Page))
- Language:
  - [x] [Basher](https://github.com/basherpm/basher) ([*issue*](https://github.com/basherpm/basher/issues/96))
  - [x] [BPKG](https://github.com/bpkg/bpkg) ([*issue*](https://github.com/bpkg/bpkg/issues/131))
  - [x] [Node.js](https://nodejs.org)
    - [x] [Yarn](https://yarnpkg.com)
    - [x] [NPM](https://www.npmjs.com)
  - [x] [PIP](https://pypi.org)
    - [x] ~~[PIPX](https://pipxproject.github.io/pipx)~~

## You can help us by summit:
- A mark (3 letter)
- A package manager tool
- A full command with flags to install packages
- A setup function
- NOTE:
  - The less user input needed the better, you should add no-confirm flag like `--noconfirm`, `--non-interactive`, `--assume-yes`, ... to the commands
  - For more Clarity, use full flag instead of short flag (E.g: use `--sync` over `-S`)

Example:
```sh
Pacman_MARK='PAC'

Pacman_PM='pacman'

Pacman_COMMAND="$PERMISSION_COMMAND $Pacman_PM --sync --noconfirm --needed"

superbbootstrap_Pacman() {
	sudo pacman --sync --sysupgrade --refresh --noconfirm --needed
}
```

> *NOTE: `$PERMISSION_COMMAND` is default to `sudo` on Linux and `doas` on BSD*

**Comment by xfzv** [comment]
I'm not a Gentoo expert by any means but here's my attempt for [Emerge](https://wiki.gentoo.org/wiki/Gentoo_Cheat_Sheet#Package_listings) ([Gentoo](https://www.gentoo.org/))


```sh
Emerge_MARK='EMG';      Emerge_COMMAND='sudo emerge --sync && sudo emerge -v'

superbbootstrap_Emerge() {
    sudo emerge --sync
    sudo emerge -vuND --with-bdeps=y @world
}

**Comment by xfzv** [comment]
Zypper (openSUSE)

```sh
Zypper_MARK='ZPR';        Zypper_COMMAND='sudo zypper refresh && sudo zypper -n install'

superbbootstrap_Zypper() {
    sudo zypper -n update       # or dist-upgrade instead? maybe overkill
}
```

**Comment by xfzv** [comment]
Just curious, why do:
- `Pacman_COMMAND`
- `XBPS_COMMAND`
- `AUR_COMMAND`

include a sync/refresh option (respectively `--refresh` ; `--sync` and `-Sy`) whereas the others just perform `install` without any sync/refresh operation?

https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L101-L107

---

The `superbbootstrap_$package_manager` functions, which are run before, all perform a sync/refresh too. Isn't it redundant to sync/refresh a second time?

https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L159-L160
https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L164-L165
https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L168-L169
https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L174-L175
https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L182-L186
https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L192-L194

If so, maybe this should now be:
| Value | Old | New |
| -------- | ---- | ------ |
| Pacman_COMMAND | `sudo pacman --sync --refresh --noconfirm --needed` | `sudo pacman --sync --noconfirm --needed` |
| XBPS_COMMAND | `sudo xbps-install --sync --yes` | `sudo xbps-install --yes` |
| AUR_COMMAND | `paru -Sy --nodiffmenu --save --noconfirm` | `paru --sync --nodiffmenu --save --noconfirm` | 
| Emerge_COMMAND | `sudo emerge --sync && sudo emerge -v` | `sudo emerge -v` |
| Zypper_COMMAND | `sudo zypper refresh && sudo zypper -n install` | `sudo zypper -n install`

**Comment by NNBnh** [comment]
> I'm not a Gentoo expert by any means but here's my attempt for [Emerge](https://wiki.gentoo.org/wiki/Gentoo_Cheat_Sheet#Package_listings) ([Gentoo](https://www.gentoo.org/))
> 
> ```shell
> Emerge_MARK='EMG';      Emerge_COMMAND='sudo emerge --sync && sudo emerge -v'
> 
> superbbootstrap_Emerge() {
>     sudo emerge --sync
>     sudo emerge -vuND --with-bdeps=y @world
> }
> ```

Thanks, this will be add to SBB 1.5.4 but i will change the mark to `PTG` because "Portage" is the package manager real name, `emerge` is just a command that come with Portage

https://wiki.gentoo.org/wiki/Portage

**Comment by NNBnh** [comment]
> Just curious, why do:
>     * `Pacman_COMMAND`
>     * `XBPS_COMMAND`
>     * `AUR_COMMAND`
> 
> include a sync/refresh option (respectively `--refresh` ; `--sync` and `-Sy`) whereas the others just perform `install` without any sync/refresh operation?
>
> The `superbbootstrap_$package_manager` functions, which are run before, all perform a sync/refresh too. Isn't it redundant to sync/refresh a second time?

Yeah... this is kinda redundant.

**Comment by xfzv** [comment]
> > Zypper (openSUSE)
> > ```shell
> > Zypper_MARK='ZPR';        Zypper_COMMAND='sudo zypper refresh && sudo zypper -n install'
> > 
> > superbbootstrap_Zypper() {
> >     sudo zypper -n update       # or dist-upgrade instead? maybe overkill
> > }
> > ```
> 
> > I'm not a Gentoo expert by any means but here's my attempt for [Emerge](https://wiki.gentoo.org/wiki/Gentoo_Cheat_Sheet#Package_listings) ([Gentoo](https://www.gentoo.org/))
> > ```shell
> > Emerge_MARK='EMG';      Emerge_COMMAND='sudo emerge --sync && sudo emerge -v'
> > 
> > superbbootstrap_Emerge() {
> >     sudo emerge --sync
> >     sudo emerge -vuND --with-bdeps=y @world
> > }
> > ```
> 
> Thanks, this will be add to SBB 1.5.4 but i will change Gentoo package manager's mark `EMG` to `PTG` because "Portage" is the package manager real name, `emerge` is just a command that come with Portage
> 
> https://wiki.gentoo.org/wiki/Portage

Indeed, `PTG` makes more sense.

> btw, do you mind if i add you name to the credits section?

No problem!

**Comment by arcadellama** [comment]
Slackware has an 'official' package manager and many unofficial third-party managers for Slackbuilds.org, which is similar to the AUR. I went with sbopkg here for the latter as it does dependency resolution with minimal user interaction, as per the gist of this script.


`
slackpkg_MARK='SLK'; slackpkg_PM='slackpkg'    ; slackpkg_COMMAND="$PERMISSION_COMMAND $slackpkg_PM install"
sbopkg_MARK='SBO';   sbopkg_PM='sbopkg'      ;   sbopkg_COMMAND="$PERMISSION_COMMAND $sbopkg_PM -ifq"
`

`
superbbootstrap_slackpkg() {
    $PERMISSION_COMMAND slackpkg update gpg
    $PERMISSION_COMMAND slackpkg update
}
`

`
superbbootstrap_sbopkg() {
    if ! command -v 'sbopkg' >/dev/null; then
	SLACKWARE_VERSION=$(awk '{print $2}' /etc/slackware-version)
	SBO_VERSION=$(curl -s https://api.github.com/repos/sbopkg/sbopkg/releases/latest | grep tag_name | awk -F':' '{print substr($2,3,length($2)-4)}')
	cd $TEMPORARY || exit 1
	$PERMISSION_COMMAND wget https://github.com/sbopkg/sbopkg/releases/download/$SBO_VERSION/sbopkg-$SBO_VERSION-noarch-1_wsr.tgz
	upgradepkg --install-new  $TEMPORARY/sbopkg-$SBO_VERSION-noarch-1_wsr.tgz
	cd $WD || exit 1
	$PERMISSION_COMMAND mkdir -p /var/lib/sbopkg/SBo/$SLACKWARE_VERSION /var/lib/sbopkg/queues /var/log/sbopkg /var/cache/sbopkg
	$PERMISSION_COMMAND sbopkg -rq
	$PERMISSION_COMMAND sqg -a
    else
	printf '%s\n' "sbopkg has been installed"
    fi
}
`
Add this to subperbbootstrap_Flatpak():
`
'SBO')      $sbopkg_COMMAND flatpak                               ;;
`

Also, to my knowledge, there isn't a SlackBuild for snapd (likely due to philosophy and the systemd work-arounds). I would suggest that testing for package manager isn't a fool-proof way to determin if Snap should be in the PACKAGEMANAGER_LIST. I would suggest doing a search by the distro instead, perhaps checking in '/etc/os-release' or similar. This is more important when you get to DNF, which could be Fedora or CentOS 8, etc., etc. Happy to work on that if desired.

**Comment by NNBnh** [comment]
@arcadellama Awesome, thank you for your contribution, This will be added to SBB 1.6.0.

Do you mind if i add you name to the credits section?

**Comment by arcadellama** [comment]
Of course, no problem.

**Comment by a4vg** [comment]
Hello again! I managed to do something for...

- ### [MacPorts](https://www.macports.org/)
I couldn't find a way to install MacPorts entirely through the CLI. It has to be installed through a .pkg installer and I don't know how to get the information to get the name of the .pkg file.
```bash
MacPorts_MARK='MCP'
MacPorts_PM='port'
MacPorts_COMMAND="$PERMISSION_COMMAND $MacPorts_PM install"

superbbootstrap_MacPorts() {
  # Install Apple's Command Line Developer Tools (will open a pop-up to confirm)
  xcode-select --install
  
  # Get MACPORT_VERSION (ex.: 2.6.4), OS_VERSION_NUMBER (ex.: 10.15) and OS_VERSION_NAME (ex.: Catalina) somehow
  macports_pkg_filename=MacPorts-$MACPORT_VERSION-$OS_VERSION_NUMBER-$OS_VERSION_NAME.pkg
  curl -O https://github.com/macports/macports-base/releases/latest/download/$macports_pkg_filename
  sudo installer -pkg $macports_pkg_filename -target /
}
```

- ### [MAS CLI](https://github.com/mas-cli/mas)
MAS can be installed with Homebrew or MacPorts, one of them should be the `PACKAGEMANAGER_MAIN` on MacOS. The script checks which was installed and uses it. MAS also requires to be signed into the AppStore, but on MacOS 10.13+ you have to sign in manually. I'm not sure on how to proceed if this is the case.

```bash
MAS_MARK='MAS'
MAS_PM='mas'
MAS_COMMAND="$MAS_PM install"

superbbootstrap_MAS() {
  if [ ! -x "$(command -v "$MAS_PM")" ]; then

    if [ -x "$(command -v "$Homebrew_PM")" ]; then
      $Homebrew_COMMAND mas
    elif [ -x "$(command -v "$MCP_PM")" ]; then
      $MacPorts_COMMAND mas
    else
      superbbootstrap_Homebrew
      $Homebrew_COMMAND mas
    fi

  else
    printf '%s\n' "MAS has been installed"
  fi

  # Sign in to the AppStore
  if ! (
        mas account &> /dev/null && # verify if user is already signed in
        mas signin --dialog $APPLE_ID # if not, try to sign in with a pop-up
       ) ; then

    # signin command failed. It is disabled on 10.13+, user has to sign in
    # directly from the AppStore
    # (stop execution, skip packages with MAS Mark, wait till the user signs in or something)

  else
    printf '%s\n' "Successfully signed in to the AppStore"
  fi
```

- ### [Brew Cask](https://github.com/Homebrew/homebrew-cask)
I dug a little more about brew cask and it seems you can install apps with `brew install app-name`. The Homebrew website uses the `--cask` flag (like [on these app](https://formulae.brew.sh/cask/anki)), but the [Homebrew Cask github](https://github.com/Homebrew/homebrew-cask) uses it without the flag. I tried on my Macbook and indeed, it works without the flag. However, it's a good practice to use the flag in case there's a package and a cask app with the same name (like [wireshark](https://formulae.brew.sh/formula/wireshark)).

Soo.. here's the script with the flag. I didn't include a HomebrewCask_PM because it's the same as Homebrew and I don't know if it's necessary.

```bash
HomebrewCask_MARK='HBC'
HomebrewCask_COMMAND="$Homebrew_PM --cask install"

superbbootstrap_HomebrewCask() {
  if [ ! -x "$(command -v "$Homebrew_PM")" ]; then
    superbbootstrap_Homebrew
  fi
}
```

There's also an easier way that doesn't need any code change. This `brew install --cask app-name` is just another way to write `brew install homebrew/cask/app-name`. So just writing `HBR:homebrew/cask/app-name` should work I guess.

- ### [Brew bundle](https://github.com/Homebrew/homebrew-bundle)
Finally, Brew bundle just installs the first time you run `brew bundle` and looks for a Brewfile in the directory. No need to implement that.


Feel free to change the code or rewrite all of it, I'm not very good at bash and it may not be the best code. If you don't own a device with MacOS I'm happy to test it if necessary (as long as I don't have to remove important stuff to reinstall them and set them up again).

**Comment by weiss-d** [comment]
`pipx` is a wonderful tool that installs Python packages just like regular PIP, but does it in isolated Python environment. That way packages and their dependencies don't interfere with system Python and with each other.
Default commands requires no sudo and no user interaction.
It's convenient way to install `youtube-dl` for example.
```sh
pipx_MARK='PIX'

pipx_PM='pipx'

pipx_COMMAND="$pipx_PM install"

superbbootstrap_pipx() {
	python3 -m pip install --user pipx
	python3 -m pipx ensurepath
}
```

**Comment by LoricAndre** [comment]
Are pip and npm still open ? I could work on them if that's the case !

**Comment by NNBnh** [comment]
Yes it is still open and i love to see your work on them ^^

**Comment by LoricAndre** [comment]
Done with https://github.com/NNBnh/superb-bootstrap/pull/18

**Comment by weiss-d** [comment]
> Done with #18
Hi, @LoricAndre! There is some problem I mentioned here:  #28
